### ISSUE TITLE
On setup:di:compile, error message is printed

### ISSUE THREAD

**Issue by nelero** [dmatthew/magento2-widget-parameters#3]
hi,
I added your code in app/code/DMatthew/WdigetParameters

Running setup:di:compile, i receive :  

> [InvalidArgumentException]
>   Plugin class Dmatthew\WidgetParameters\Block\Plugin\Adminhtml\Wysiwyg\Images\Content doesn't exist

How to fix this ? 
Thanks

**Comment by dmatthew** [comment]
@nelero It looked like a file was missing. I added the missing file. Try it out again with the master branch.

**Comment by nelero** [comment]
@dmatthew thanks, it works !
