### ISSUE TITLE
Open Image Chooser ends up with 404

### ISSUE THREAD

**Issue by upandfine** [dmatthew/magento2-widget-parameters#4]
Open Image Chooser ends up with 404.
Button-URL:
`MediabrowserUtility.openDialog('http://magento2.shop.local:4080/kdp_admin/cms/wysiwyg_images/index/target_element_id/options_fieldset90a65f7c709fd10e72250fe7050b9f53_first_image/on_insert_url/http%3A%2F%2Fmagento2.shop.local%3A4080%2Fkdp_admin%2Fdmatthew_widgettypes%2Fwysiwyg_images%2FonInsert%2Fkey%2F086d0e0fe901d3f88ed35fc12dbb9973bf1e31f93b3ef6cc6aae90b207ce4f48%2F/key/edd3bce0406ba2b20943cfe77c74499adb47baebaaf1cc2fb6ab4bf35b61cd57/', 0, 0, "Insert File...", {})`

Edit: Magento 2.2.5

**Comment by ubermanu** [comment]
It should be fixed with the MR #5
